config/routes.rb
Shoutit::Application.routes.draw do

  devise_for :users

  resources :shouts

  match "shouts/:id/vote", to: "votes#create", :as => "shout_vote", via: [:get, :post]

  authenticated :user do
    root :to => "shouts#new", as: :authenticated_root
  end
  unauthenticated do
    root :to => "static_pages#home"
  end

end

app/models/shout.rb
class Shout < ActiveRecord::Base
	belongs_to :user, :class_name => :User, :foreign_key => :user
	def self.create_shout(shout_params)
		shout = Shout.create(
			# :title => move_params[:title]
			# :time_start => Time.now,
			:text => shout_params[:text],
			# :name => shout_params[:name],
			# :twitter => shout_params[:twitter],
			# :color => shout_params[:color],
			# :user => current_user,
			:expires_at => Time.now+1.hour,
			:active => true
		)
	    shout
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :shouts, :class_name => :Shout, :foreign_key => :user, :dependent => :delete_all
  has_many :votes, :class_name => :Vote, :foreign_key => :vote
end

app/models/vote.rb
# == Schema Information
#
# Table name: votes
#
#  id     :integer          not null, primary key
#  voter  :integer
#  type   :string(255)
#  value  :integer
#  fight  :integer
#  user   :integer
#  attack :integer
#

class Vote < ActiveRecord::Base
  belongs_to :shout, :class_name => :Shout, :foreign_key => :shout
  belongs_to :user, :class_name => :User, :foreign_key => :user

  def self.create_vote(vote_params)
    @vote = Vote.create!(
        # :voter => current_user.id,
        # :fight => Fight.find_by_id(vote_params[:fight]),
        # :user => User.find_by_id(vote_params[:user]),
      )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/shouts_controller.rb
class ShoutsController < ApplicationController
	def new
		@shout = Shout.new
		@shouts = Shout.all
	end
	def create
		@shout = Shout.new
		if @shout.valid?
			@shout = Shout.create_shout(shout_params)
			redirect_to shout_path(@shout)
		else 
			validation_messages = @shout.errors.messages.to_s
			flash[:error] = error_message
			render 'new'
		end
	end

	def show
		@shout = Shout.find params[:id]
	end

	private
	    def shout_params
	      params.require(:shout).permit(
	        :id,
	        :text,
	        :name,
	        :twitter,
	        :color
	      )
	    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @shouts = Shout.all
  end
end 

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def new
    @vote = Vote.new
  end

  def create
    @vote = Vote.create_vote(vote_params)
    if @vote.id
      redirect_to :back, :notice => "Your vote has been added!"
    else
      redirect_to :back, :notice => "Sorry, that vote didn't go through. Try again?"
    end
  end
  def shout_vote
    @shout = Shout.find params[:id]
  end

  private
    def vote_params
      params.require(:vote).permit(
        :voter,
        :type,
        :value,
        :user,
      )
    end
end 

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.       # Documentation comment
  def full_title(page_title)                          # Method definition
    base_title = "Shout Club"  # Variable assignment
    if page_title.empty?                              # Boolean test
      base_title                                      # Implicit return
    else
      "#{base_title} | #{page_title}"                 # String interpolation
    end
  end
  def body_id(page_id)
      "#{page_id}"
  end

  def body_class(page_class)
      "#{page_class}"
  end
end

app/helpers/shouts_helper.rb
module ShoutsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shoutit</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <script src="//use.typekit.net/nnq6gqc.js"></script>
  <script>try{Typekit.load();}catch(e){}</script>
  <%= csrf_meta_tags %>
</head>
<body id="<%= body_id(yield(:body_id)) %>" class="<%= body_class(yield(:body_class)) %>">
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>
  <section class="global-header">
    <a href="/">ishh</a>

    <ul>
      <% if user_signed_in? %>
        <li class="parent"><a href="#"><%= current_user.first_name %> <%= current_user.last_name %><span class="caret">&#9660;</b></a>
          <ul class="children">
            <li><%= link_to 'Edit Account', edit_user_registration_path %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path, :class => "button small" %> 
        <%= link_to "Login", new_user_session_path, :class => "button small" %>
      <% end %>
    </ul>
  </section>
<%= yield %>

</body>
</html>

app/views/shouts/_shouts.html.erb
<div class="shouts">
  <ul>
    <% @shouts.each do |shout| %>
      <li><%= link_to shout.text, shout_path(shout) %></li>
    <% end %>
  </ul>
</div>

app/views/shouts/new.html.erb
<% provide(:body_class, 'new-shout home') %>
<div class="container">
  <div class="form-wrap">
    <!-- <h1>Shout something</h1> -->
    <%= form_for(@shout) do |f| %>
      <%# render 'shared/error_messages', object: f.object %>
      <div class="field-wrap">
        <div class="form-group">
          <%= f.text_field :text, :class => "text ish", :placeholder => "ish...", :required => "required", :autofocus => true, :tabindex => '1' %>
        </div>
        <div class="form-group">
          <%= f.text_field :color, :class => "color background-color", :placeholder => "HEX", :tabindex => '4' %>
        </div>
        <div class="form-group">
          <%= f.text_field :color, :class => "color text-color", :placeholder => "HEX", :tabindex => '4' %>
        </div>
      </div>
      <%= f.submit "Publish", class: "button" %>
    <% end %>
  </div>
  <div class="shouts">
    <ul>
    <% @shouts.each do |shout| %>
      <li><%= link_to shout.text, shout_path(shout) %></li>
    <% end %>
    </ul>
  </div>
</div>

app/views/shouts/show.html.erb
<% provide(:body_class, 'shout') %>
<div class="container">
  <div class="countdown">
    <p class="hide"><%= @shout.expires_at %></p>
    <span class="down"></span>
  </div>
  <div class="shout-wrap">
    <h1><span><%= @shout.text %></span></h1>
    <% if @shout.name %>
      <p class="name"><%= @shout.name %></p>
    <% end %>
    <% if @shout.twitter %>
      <p class="twitter"><%= @shout.twitter %></p>
    <% end %>
  </div>
  <%# link_to 'Like', shout_vote_path(@shout), :class => "button" %>
</div>

app/views/static_pages/home.html.erb
<% provide(:body_class, 'home') %>
<%= render 'shouts/shouts' %>